// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using MusicShop.Data;

#nullable disable

namespace MusicShop.Migrations
{
    [DbContext(typeof(ShopContext))]
    partial class ShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MusicShop.Models.BasketEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BuyerId")
                        .HasColumnType("integer");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("InstrumentId");

                    b.ToTable("BasketEntries");
                });

            modelBuilder.Entity("MusicShop.Models.Buyer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Buyers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryAddress = "Санкт-Петербург, Музыкальная ул., 7",
                            Email = "dmitry@example.com",
                            FullName = "Дмитрий Волков",
                            JoinedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Phone = "+7-999-876-54-32"
                        });
                });

            modelBuilder.Entity("MusicShop.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new { Id = 1, Summary = "Акустические, электрогитары, бас-гитары, классические", Title = "Гитары и бас-гитары" },
                        new { Id = 2, Summary = "Цифровые пианино, синтезаторы, MIDI-клавиатуры, органы", Title = "Клавишные и синтезаторы" },
                        new { Id = 3, Summary = "Акустические и электронные барабаны, перкуссия, тарелки", Title = "Ударные инструменты" },
                        new { Id = 4, Summary = "Скрипки, виолончели, контрабасы, укулеле", Title = "Струнные инструменты" },
                        new { Id = 5, Summary = "Саксофоны, трубы, флейты, кларнеты, тромбоны", Title = "Духовые инструменты" });
                });

            modelBuilder.Entity("MusicShop.Models.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ListedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Overview")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("RetailPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Instruments");

                    b.HasData(
                        new { Id = 1, CoverUrl = "https://placehold.co/300x300/13111c/a855f7?text=Guitar", GenreId = 1, ListedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), Overview = "Классическая акустическая гитара для начинающих и любителей. Корпус из выдержанной ели и меранти, яркий открытый звук.", RetailPrice = 12900m, StockCount = 34, Title = "Yamaha F310 Natural" },
                        new { Id = 2, CoverUrl = "https://placehold.co/300x300/1e0a3c/c084fc?text=Stratocaster", GenreId = 1, ListedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), Overview = "Легендарная электрогитара с тремя синглами. Кленовый гриф, корпус из ольхи, современная C-образная шейка.", RetailPrice = 89000m, StockCount = 12, Title = "Fender Player Stratocaster SSS" },
                        new { Id = 3, CoverUrl = "https://placehold.co/300x300/0f0c29/818cf8?text=Piano", GenreId = 2, ListedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), Overview = "Профессиональное сценическое пианино с 88 взвешенными клавишами. Механика SuperNATURAL, 128 голосов полифонии.", RetailPrice = 149000m, StockCount = 6, Title = "Roland RD-88 Stage Piano" },
                        new { Id = 4, CoverUrl = "https://placehold.co/300x300/1a0a2e/a78bfa?text=Casio", GenreId = 2, ListedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), Overview = "Компактный синтезатор для обучения. 61 клавиша, 48 голосов полифонии, 400 тембров, встроенные ритмы.", RetailPrice = 8900m, StockCount = 55, Title = "Casio CT-S300 Casiotone" },
                        new { Id = 5, CoverUrl = "https://placehold.co/300x300/1c1917/d97706?text=Drums", GenreId = 3, ListedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), Overview = "Профессиональная барабанная установка из 5 предметов. Корпуса из тополя и берёзы, хромированная фурнитура.", RetailPrice = 79000m, StockCount = 8, Title = "Pearl Export EXX 5-Piece" },
                        new { Id = 6, CoverUrl = "https://placehold.co/300x300/1c0a0a/f87171?text=Violin", GenreId = 4, ListedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), Overview = "Студенческая скрипка полного размера из выдержанной ели и клёна. Поставляется в комплекте со смычком и футляром.", RetailPrice = 18500m, StockCount = 22, Title = "Cremona SV-175 Скрипка 4/4" },
                        new { Id = 7, CoverUrl = "https://placehold.co/300x300/1a1200/fbbf24?text=Saxophone", GenreId = 5, ListedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), Overview = "Студенческий альт-саксофон из жёлтой латуни с лакировкой. Удобная эргономика клапанов, стабильный строй.", RetailPrice = 89000m, StockCount = 9, Title = "Yamaha YAS-280 Alto Saxophone" },
                        new { Id = 8, CoverUrl = "https://placehold.co/300x300/0a0a1a/6366f1?text=Korg+Volca", GenreId = 2, ListedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), Overview = "Аналоговый бас-синтезатор с секвенсором на 16 шагов. 3 генератора, фильтр LFO, MIDI In, встроенный динамик.", RetailPrice = 14900m, StockCount = 18, Title = "Korg Volca Bass Synthesizer" });
                });

            modelBuilder.Entity("MusicShop.Models.InstrumentSpecs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("GuaranteeMonths")
                        .HasColumnType("integer");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer");

                    b.Property<double?>("MassKg")
                        .HasColumnType("double precision");

                    b.Property<string>("Origin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SizeInfo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId")
                        .IsUnique();

                    b.ToTable("InstrumentSpecs");

                    b.HasData(
                        new { Id = 1, Brand = "Yamaha", GuaranteeMonths = 12, InstrumentId = 1, MassKg = 1.9, Origin = "Япония", SizeInfo = "Дредноут, мензура 650 мм" },
                        new { Id = 2, Brand = "Fender", GuaranteeMonths = 24, InstrumentId = 2, MassKg = 3.6, Origin = "Мексика", SizeInfo = "Корпус ольха, гриф клён 648 мм" },
                        new { Id = 3, Brand = "Roland", GuaranteeMonths = 24, InstrumentId = 3, MassKg = 18.5, Origin = "Япония", SizeInfo = "1375 × 302 × 139 мм" },
                        new { Id = 4, Brand = "Casio", GuaranteeMonths = 12, InstrumentId = 4, MassKg = 3.3, Origin = "Япония", SizeInfo = "905 × 258 × 73 мм" },
                        new { Id = 5, Brand = "Pearl", GuaranteeMonths = 36, InstrumentId = 5, MassKg = 52.0, Origin = "Тайвань", SizeInfo = "бочка 22\", томы 10\"/12\"/16\", малый 14\"" },
                        new { Id = 6, Brand = "Cremona", GuaranteeMonths = 6, InstrumentId = 6, MassKg = 0.42, Origin = "Чехия", SizeInfo = "4/4, дека ель, обечайки клён" });
                });

            modelBuilder.Entity("MusicShop.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShipTo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("MusicShop.Models.PurchaseEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceAtSale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("integer");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseEntries");
                });

            modelBuilder.Entity("MusicShop.Models.BasketEntry", b =>
                {
                    b.HasOne("MusicShop.Models.Buyer", "Buyer")
                        .WithMany("BasketEntries")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicShop.Models.Instrument", "Instrument")
                        .WithMany("BasketEntries")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");
                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("MusicShop.Models.Instrument", b =>
                {
                    b.HasOne("MusicShop.Models.Genre", "Genre")
                        .WithMany("Instruments")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MusicShop.Models.InstrumentSpecs", b =>
                {
                    b.HasOne("MusicShop.Models.Instrument", "Instrument")
                        .WithOne("Specs")
                        .HasForeignKey("MusicShop.Models.InstrumentSpecs", "InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("MusicShop.Models.Purchase", b =>
                {
                    b.HasOne("MusicShop.Models.Buyer", "Buyer")
                        .WithMany("Purchases")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("MusicShop.Models.PurchaseEntry", b =>
                {
                    b.HasOne("MusicShop.Models.Instrument", "Instrument")
                        .WithMany("PurchaseEntries")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MusicShop.Models.Purchase", "Purchase")
                        .WithMany("Entries")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("MusicShop.Models.Buyer", b =>
                {
                    b.Navigation("BasketEntries");
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("MusicShop.Models.Genre", b =>
                {
                    b.Navigation("Instruments");
                });

            modelBuilder.Entity("MusicShop.Models.Instrument", b =>
                {
                    b.Navigation("BasketEntries");
                    b.Navigation("PurchaseEntries");
                    b.Navigation("Specs");
                });

            modelBuilder.Entity("MusicShop.Models.Purchase", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
